# Generated by Django 3.0.4 on 2020-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPermiso', models.CharField(choices=[('ENFERMEDAD', 'ENFERMEDAD'), ('COMPENSACION', 'COMPENSACION'), ('CALAMIDAD', 'CALAMIDAD'), ('CERTIFICADO', 'CERTIFICADO')], default='ENFERMEDAD', max_length=15)),
                ('nombreCompleto', models.CharField(max_length=30)),
                ('fechaDesde', models.DateField(verbose_name='fecha de desde')),
                ('fechaHasta', models.DateField(verbose_name='fecha de hasta')),
                ('numeroDias', models.IntegerField(max_length=10)),
            ],
        ),
    ]
